## Data Manupulation:-
### Adding new column:-

In [8]:
import pandas as pd
my_data = {
    'Name':['A','B','C','D','E'],
    'Age':[20,21,22,24,19],
    'City':["Delhi",'Kolkata','Pune','Mumbai','Delhi'],
    'marks':[88,76,92,44,59]
}
df = pd.DataFrame(my_data)
df['Dept'] = ['CSE','ECE',None,'ITI','EEE']

df

  Name  Age     City  marks  Dept
0    A   20    Delhi     88   CSE
1    B   21  Kolkata     76   ECE
2    C   22     Pune     92  None
3    D   24   Mumbai     44   ITI
4    E   19    Delhi     59   EEE

my_data =

In [10]:
df.iloc[0,3] = 82
df

  Name  Age     City  marks  Dept
0    A   20    Delhi     82   CSE
1    B   21  Kolkata     76   ECE
2    C   22     Pune     92  None
3    D   24   Mumbai     44   ITI
4    E   19    Delhi     59   EEE

In [11]:
df.loc[0:2,'marks'] = 24
df

  Name  Age     City  marks  Dept
0    A   20    Delhi     24   CSE
1    B   21  Kolkata     24   ECE
2    C   22     Pune     24  None
3    D   24   Mumbai     44   ITI
4    E   19    Delhi     59   EEE

In [12]:
df.iloc[0:2,3] = 12
df

  Name  Age     City  marks  Dept
0    A   20    Delhi     12   CSE
1    B   21  Kolkata     12   ECE
2    C   22     Pune     24  None
3    D   24   Mumbai     44   ITI
4    E   19    Delhi     59   EEE

In [13]:
print(df)

  Name  Age     City  marks  Dept
0    A   20    Delhi     12   CSE
1    B   21  Kolkata     12   ECE
2    C   22     Pune     24  None
3    D   24   Mumbai     44   ITI
4    E   19    Delhi     59   EEE