In [18]:
my_data = {
    "Employee Name":["Shubham Jana","Sujoy Roy","Rohan Bose","Dipak Jana","Pritam Ghorai","Nirmal Bera"],
    "Salary" : [45000,46000,70000,56000,60000,80000],
    "Gender" : ["Male","Male","Female","Male","Female","Male"],
    "Address": ["Kolkata","Mumbai","Delhi","Pune","Washington DC","Hydrabad"],
    "Department": ["IT","HR","Salse","IT","HR","Salse"],
    "Country" : ["India","Bangla Desh","India","USA","India","India"]
}

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(my_data)

In [21]:
df

   Employee Name  Salary  Gender        Address Department      Country
0   Shubham Jana   45000    Male        Kolkata         IT        India
1      Sujoy Roy   46000    Male         Mumbai         HR  Bangla Desh
2     Rohan Bose   70000  Female          Delhi      Salse        India
3     Dipak Jana   56000    Male           Pune         IT          USA
4  Pritam Ghorai   60000  Female  Washington DC         HR        India
5    Nirmal Bera   80000    Male       Hydrabad      Salse        India

In [22]:
my_gr1 = df.groupby("Gender")["Gender"].count()
my_gr1

Gender
Female    2
Male      4
Name: Gender, dtype: int64

In [24]:
my_groupby2 = df.groupby("Employee Name")["Department"].count()
my_groupby2

Employee Name
Dipak Jana       1
Nirmal Bera      1
Pritam Ghorai    1
Rohan Bose       1
Shubham Jana     1
Sujoy Roy        1
Name: Department, dtype: int64

In [25]:
group_by_3 = df.groupby("Department")["Gender"].count()
group_by_3

Department
HR       2
IT       2
Salse    2
Name: Gender, dtype: int64

In [27]:
group_by_4 = df.groupby("Employee Name")["Salary"].mean()
group_by_4

Employee Name
Dipak Jana       56000.0
Nirmal Bera      80000.0
Pritam Ghorai    60000.0
Rohan Bose       70000.0
Shubham Jana     45000.0
Sujoy Roy        46000.0
Name: Salary, dtype: float64

In [28]:
group_by_5 = df.groupby("Department")["Salary"].mean()
group_by_5

Department
HR       53000.0
IT       50500.0
Salse    75000.0
Name: Salary, dtype: float64

Perfrom Summation operation on the the salary column by the help of group by with "Department" column. :)

In [29]:
group_by_6 = df.groupby("Department")["Salary"].sum()
group_by_6

Department
HR       106000
IT       101000
Salse    150000
Name: Salary, dtype: int64

In [31]:
group_by_7 = df.groupby("Country")["Employee Name"].count()
group_by_7

Country
Bangla Desh    1
India          4
USA            1
Name: Employee Name, dtype: int64

In [32]:
group_by_8 = df.groupby("Country")["Salary"].sum()
group_by_8

Country
Bangla Desh     46000
India          255000
USA             56000
Name: Salary, dtype: int64

Perform Multiple aggregade function by the help of groupby ***Asking Gemini to Shut its mouth up beacuse I am learning these***

In [34]:
multi_agg = df.groupby("Department").agg({"Salary":["mean","sum","count"]})

In [39]:
multi_agg = df.groupby("Department").agg({"Salary":["mean","sum","count"]})
display(multi_agg)

             Salary
               mean     sum count
Department
HR          53000.0  106000     2
IT          50500.0  101000     2
Salse       75000.0  150000     2

In [38]:
print(multi_agg)

             Salary
               mean     sum count
Department
HR          53000.0  106000     2
IT          50500.0  101000     2
Salse       75000.0  150000     2

In [37]:
display("Gemini is a bad guy")

'Gemini is a bad guy'

In [41]:
df.groupby("Department").agg({
    'Salary':['mean','min','max'],
    "Department":'count'
})

             Salary               Department
               mean    min    max      count
Department
HR          53000.0  46000  60000          2
IT          50500.0  45000  56000          2
Salse       75000.0  70000  80000          2

In [44]:
df.pivot_table(
    values = "Salary",
    index = "Department",
    columns="Gender",
    aggfunc = ["mean","sum","min","max",]
)

               mean               sum                min               max  \
Gender       Female     Male   Female      Male   Female     Male   Female
Department
HR          60000.0  46000.0  60000.0   46000.0  60000.0  46000.0  60000.0
IT              NaN  50500.0      NaN  101000.0      NaN  45000.0      NaN
Salse       70000.0  80000.0  70000.0   80000.0  70000.0  80000.0  70000.0


Gender         Male
Department
HR          46000.0
IT          56000.0
Salse       80000.0

In [46]:
df['Average Salary'] = df.groupby("Department")["Salary"].transform("mean")
display(df['Average Salary'])

0    50500.0
1    53000.0
2    75000.0
3    50500.0
4    53000.0
5    75000.0
Name: Average Salary, dtype: float64

In [48]:
display(df.groupby("Department").filter(
    lambda x: x['Salary'].mean()>70000
))

  Employee Name  Salary  Gender   Address Department Country  Average Salary
2    Rohan Bose   70000  Female     Delhi      Salse   India         75000.0
5   Nirmal Bera   80000    Male  Hydrabad      Salse   India         75000.0