in rows and columns. It's one of the most comonly use tool for handleing data and makes it easy to organize analize and manupulate data.

In [8]:
import pandas as pd

In [9]:
lis = ['A','B','C','D']
df = pd.DataFrame(lis)
print(df)

   0
0  A
1  B
2  C
3  D

In [10]:
dict = {"Name":['a','b','c'],"Roll":[23,45,66]}
df = pd.DataFrame(dict)
df

  Name  Roll
0    a    23
1    b    45
2    c    66

### Atributes:
* shpae, size, ndim, columns, index, dtypes

In [11]:
df2 = pd.DataFrame({"Name":["Shubham","Rahul","Danish","Dipak"],"Roll":[102,223,432,456],"Subject":["Math","Physics","Biology","Chemistry"]})
df2

      Name  Roll    Subject
0  Shubham   102       Math
1    Rahul   223    Physics
2   Danish   432    Biology
3    Dipak   456  Chemistry

In [12]:
print(df2["Name"])
print(type(df2["Name"]))
print(df2[["Name","Subject"]])

0    Shubham
1      Rahul
2     Danish
3      Dipak
Name: Name, dtype: object
<class 'pandas.core.series.Series'>
      Name    Subject
0  Shubham       Math
1    Rahul    Physics
2   Danish    Biology
3    Dipak  Chemistry

In [13]:
print(df2["Roll"][1])

223

In [14]:
print(df2.loc[1,"Roll"])
print(df2.loc[1])

223
Name         Rahul
Roll           223
Subject    Physics
Name: 1, dtype: object

#### Slicing in Row:

In [15]:
print(df2.iloc[0:2])
print(df2['Roll']<122)

      Name  Roll  Subject
0  Shubham   102     Math
1    Rahul   223  Physics
0     True
1    False
2    False
3    False
Name: Roll, dtype: bool

In [16]:

df2[df2["Roll"]<122]
print(df2["Roll"].mean())

303.25

In [17]:
df2.groupby("Name")["Roll"].mean()

Name
Danish     432.0
Dipak      456.0
Rahul      223.0
Shubham    102.0
Name: Roll, dtype: float64

In [29]:
df3 = pd.read_csv('employees.csv')
print(df3["Salary"].mean())
print(df3.groupby("Name")["Salary"].max())

61116.666666666664
Name
Bob Johnson       55000
Charlie Davis     52000
Fiona Garcia      75000
Hannah Jackson    48000
Ivan Lee          72000
John Doe          50000
Kevin White       67000
Lisa Chen         73000
Nancy Taylor      49000
Oliver Brown      51000
Quinn Davis       56000
Uma Patel         66000
alice brown       65000
diana martinez    58000
evan wilson       60000
george thomas     65000
jane smith        65000
julia anderson    51000
michael jones     64000
patricia white    71000
robert martin     74000
sophia lewis      50000
thomas garcia     62000
victor santos     52000
wendy brown       72500
zoe johnson       63000
Name: Salary, dtype: int64

In [33]:
# result = df3[df3["Salary"]<50000]["Name"]
# result[["Name","Salary"]]
# result
print(df3["Salary"][1])

65000

In [28]:
df3["Salary"] = str(df3["Salary"])
print(df3["Salary"][1])

0     0     50000\n1     65000\n2     55000\n3     6...
1     0     50000\n1     65000\n2     55000\n3     6...
2     0     50000\n1     65000\n2     55000\n3     6...
3     0     50000\n1     65000\n2     55000\n3     6...
4     0     50000\n1     65000\n2     55000\n3     6...
5     0     50000\n1     65000\n2     55000\n3     6...
6     0     50000\n1     65000\n2     55000\n3     6...
7     0     50000\n1     65000\n2     55000\n3     6...
8     0     50000\n1     65000\n2     55000\n3     6...
9     0     50000\n1     65000\n2     55000\n3     6...
10    0     50000\n1     65000\n2     55000\n3     6...
11    0     50000\n1     65000\n2     55000\n3     6...
12    0     50000\n1     65000\n2     55000\n3     6...
13    0     50000\n1     65000\n2     55000\n3     6...
14    0     50000\n1     65000\n2     55000\n3     6...
15    0     50000\n1     65000\n2     55000\n3     6...
16    0     50000\n1     65000\n2     55000\n3     6...
17    0     50000\n1     65000\n2     55000\n3     6...
18    0     50000\n1     65000\n2     55000\n3     6...
19    0     50000\n1     65000\n2     55000\n3     6...
20    0     50000\n1     65000\n2     55000\n3     6...
21    0     50000\n1     65000\n2     55000\n3     6...
22    0     50000\n1     65000\n2     55000\n3     6...
23    0     50000\n1     65000\n2     55000\n3     6...
24    0     50000\n1     65000\n2     55000\n3     6...
25    0     50000\n1     65000\n2     55000\n3     6...
26    0     50000\n1     65000\n2     55000\n3     6...
27    0     50000\n1     65000\n2     55000\n3     6...
28    0     50000\n1     65000\n2     55000\n3     6...
29    0     50000\n1     65000\n2     55000\n3     6...
Name: Salary, dtype: object

In [21]:
print(df3["Name"].max())

TypeError: '>=' not supported between instances of 'str' and 'float'

In [ ]:
result2 = df3[df3["Name"].max()]["Name"]
result2

TypeError: '>=' not supported between instances of 'str' and 'float'

* Viewing
* Data information
* Checheing Shape, Size, Calumn
* Unique values
* Value count

In [ ]:
print(df3.head())

  EmployeeID         Name   Department  Salary JoiningDate
0       E001     John Doe           HR   50000  2020-01-15
1       E002   jane smith           IT   65000  2019-03-22
2       E003  Bob Johnson        SALES   55000         NaN
3       E004  alice brown           IT   65000  2021-02-10
4       E005          NaN  Engineering   70000  2018-05-30

IF we do not put any value as parameter then .head() will return first 5 values of the data set.

In [37]:
print(df3.tail(7))

   EmployeeID           Name   Department  Salary JoiningDate
23       E024   sophia lewis    Marketing   50000  2022-02-14
24       E025  thomas garcia          NaN   62000  2020-09-09
25       E026      Uma Patel           IT   66000  2021-03-25
26       E027  victor santos           HR   52000  2019-12-01
27       E028    wendy brown  Engineering   72500         NaN
28       E029            NaN        SALES   54000  2020-08-17
29       E030    zoe johnson           it   63000  2021-06-06

IF we do not put any value as parameter then .tail() will return last 5 values of the data set.

### Data Infarmation:
* -- info()
* -- describe()
* -- describe(includ = 'object')

In [38]:
print(df3.describe(include= 'object'))

       EmployeeID      Name Department JoiningDate
count          30        26         28          26
unique         30        26         10          26
top          E001  John Doe         IT  2020-01-15
freq            1         1          7           1

In [39]:
print(df3.describe())

             Salary
count     30.000000
mean   61116.666667
std     8685.782411
min    48000.000000
25%    52500.000000
50%    62500.000000
75%    67750.000000
max    75000.000000

In [42]:
print(len(df3))

30

### Unique Values:
* -- unique() <br>
It returns the unique values in a data frame.
* -- nunique() <br>
It returns the count of the unique values of a data frame.

In [43]:
print(df3.nunique)

<bound method DataFrame.nunique of    EmployeeID            Name   Department  Salary JoiningDate
0        E001        John Doe           HR   50000  2020-01-15
1        E002      jane smith           IT   65000  2019-03-22
2        E003     Bob Johnson        SALES   55000         NaN
3        E004     alice brown           IT   65000  2021-02-10
4        E005             NaN  Engineering   70000  2018-05-30
5        E006   Charlie Davis           hr   52000  2022-01-01
6        E007  diana martinez        Sales   58000  2020-11-20
7        E008     evan wilson          NaN   60000  2019-07-14
8        E009    Fiona Garcia  Engineering   75000  2021-04-05
9        E010   george thomas           IT   65000  2020-06-18
10       E011  Hannah Jackson    MARKETING   48000         NaN
11       E012        Ivan Lee  Engineering   72000  2019-09-12
12       E013  julia anderson           hr   51000  2022-03-08
13       E014     Kevin White           IT   67000  2020-12-25
14       E015             NaN        Sales   55000  2021-01-30
15       E016       Lisa Chen  Engineering   73000  2018-08-22
16       E017   michael jones           IT   64000  2019-10-15
17       E018    Nancy Taylor    MARKETING   49000  2020-02-28
18       E019    Oliver Brown           HR   51000         NaN
19       E020  patricia white  Engineering   71000  2021-07-11
20       E021     Quinn Davis        sales   56000  2020-05-20
21       E022             NaN           IT   68000  2019-11-03
22       E023   robert martin  Engineering   74000  2018-04-12
23       E024    sophia lewis    Marketing   50000  2022-02-14
24       E025   thomas garcia          NaN   62000  2020-09-09
25       E026       Uma Patel           IT   66000  2021-03-25
26       E027   victor santos           HR   52000  2019-12-01
27       E028     wendy brown  Engineering   72500         NaN
28       E029             NaN        SALES   54000  2020-08-17
29       E030     zoe johnson           it   63000  2021-06-06>

In [47]:
print(df3["Name"].unique())

['John Doe' 'jane smith' 'Bob Johnson' 'alice brown' nan 'Charlie Davis'
 'diana martinez' 'evan wilson' 'Fiona Garcia' 'george thomas'
 'Hannah Jackson' 'Ivan Lee' 'julia anderson' 'Kevin White' 'Lisa Chen'
 'michael jones' 'Nancy Taylor' 'Oliver Brown' 'patricia white'
 'Quinn Davis' 'robert martin' 'sophia lewis' 'thomas garcia' 'Uma Patel'
 'victor santos' 'wendy brown' 'zoe johnson']

In [46]:
print(df3["Salary"].unique())

[50000 65000 55000 70000 52000 58000 60000 75000 48000 72000 51000 67000
 73000 64000 49000 71000 56000 68000 74000 62000 66000 72500 54000 63000]

In [49]:
print(df3["Salary"].value_counts())

Salary
65000    3
50000    2
55000    2
52000    2
51000    2
49000    1
54000    1
72500    1
66000    1
62000    1
74000    1
68000    1
56000    1
71000    1
73000    1
64000    1
67000    1
72000    1
48000    1
75000    1
60000    1
58000    1
70000    1
63000    1
Name: count, dtype: int64

In [51]:
print(df3["Salary"].value_counts(normalize=True))

Salary
65000    0.100000
50000    0.066667
55000    0.066667
52000    0.066667
51000    0.066667
49000    0.033333
54000    0.033333
72500    0.033333
66000    0.033333
62000    0.033333
74000    0.033333
68000    0.033333
56000    0.033333
71000    0.033333
73000    0.033333
64000    0.033333
67000    0.033333
72000    0.033333
48000    0.033333
75000    0.033333
60000    0.033333
58000    0.033333
70000    0.033333
63000    0.033333
Name: proportion, dtype: float64

In [1]:
import pandas as pd

In [5]:
Data_set = [(1,"Shubham",'DSA',"Kolkata"),
            (2,"Raghab",'Data scince',"Delhi"),
            (3,"Dipanjan",'AI and ML',"Medinipur"),
            (4,"Raman","DBMS","Tamluk")]
student_data = pd.DataFrame(Data_set,columns=['Student ID', 'Name','Course Name','Address'])
student_data

   Student ID      Name  Course Name    Address
0           1   Shubham          DSA    Kolkata
1           2    Raghab  Data scince      Delhi
2           3  Dipanjan    AI and ML  Medinipur
3           4     Raman         DBMS     Tamluk