# Data cleaning:-

### Missing Values:-
* in pandas miossing data occurs when some values are missing or not collected properly this misssing values are represented as NaN, None.
* Pansa provides 2 importtant functions which help detecting missing values:-
* .isnull()
* returns a data frame of boolen values where true represent missing data

In [19]:
import pandas as pd
data = {
    'Name': ['Amit','Priya', 'Rohit', None, 'Daa'],
    'Marks': [34,None,90,75,85]
}
df = pd.DataFrame(data)
print("Where value is persent\n")
df.isnull()
# df

Where value is persent

    Name  Marks
0  False  False
1  False   True
2  False  False
3   True  False
4  False  False

#### df.isnull().sum() 
* count the missing values per column -> df.isnull().sum()
* count the total missing value in the data Frame -> df.isnull().sum()

In [20]:
df.isnull().sum()

Name     1
Marks    1
dtype: int64

In [21]:
df.isnull().sum().sum()

np.int64(2)

##### .fillna(parameter)
* This function allow us to replace missing values with a specified value.
##### fillna()
* This is used replace missing values with a specific value

In [11]:
df.fillna("Unknown")

      Name    Marks
0     Amit     34.0
1    Priya  Unknown
2    Rohit     90.0
3  Unknown     75.0
4      Daa     85.0

In [13]:
df["Marks"] = df["Marks"].fillna(56)

In [14]:
df

    Name  Marks
0   Amit   34.0
1  Priya   56.0
2  Rohit   90.0
3   None   75.0
4    Daa   85.0

ffill(), bifill

In [17]:
print(df.ffill(axis=1))
print(df.bfill(axis=0))

    Name Marks
0   Amit  34.0
1  Priya  56.0
2  Rohit  90.0
3    NaN  75.0
4    Daa  85.0
    Name  Marks
0   Amit   34.0
1  Priya   56.0
2  Rohit   90.0
3    Daa   75.0
4    Daa   85.0

/var/folders/hp/4dy5d7xd0gs9n9hmjyh3fx9r0000gn/T/ipykernel_8575/1640217195.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  print(df.ffill(axis=1))

In [18]:
data1 = {
    'Name': ['Amit','Priya', 'Rohit', None, 'Daa'],
    'Marks': [34,None,90,75,85]
}
df1 = pd.DataFrame(data1)