<a href="https://colab.research.google.com/github/Shubham-Jana-Dev/Data-Science/blob/main/Pandas_Practice/Pandas_missing_value_handeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Charlie', None,'David'],
    'Age': [25, None, 30, None,22],
    'Score': [85.5, 90.0, None, None, 88.0],
    'City': ['New York', 'Los Angeles', None, None,'Chicago']
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
display(df)

      Name   Age  Score         City
0    Alice  25.0   85.5     New York
1      Bob   NaN   90.0  Los Angeles
2  Charlie  30.0    NaN         None
3     None   NaN    NaN         None
4    David  22.0   88.0      Chicago

In [ ]:
dfe = df.dropna(how="any")
display(dfe)

    Name   Age  Score      City
0  Alice  25.0   85.5  New York
4  David  22.0   88.0   Chicago

In [ ]:
df["Score"] = df["Score"].fillna(0)

In [ ]:
display(df)

      Name   Age  Score         City
0    Alice  25.0   85.5     New York
1      Bob   NaN   90.0  Los Angeles
2  Charlie  30.0    0.0         None
3    David  22.0   88.0      Chicago