<a href="https://colab.research.google.com/github/Shubham-Jana-Dev/Data-Science/blob/main/Pandas/02_Pandas_Data_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('sample_data/data.csv')

In [ ]:
display(df.head())

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [ ]:
display(df.iloc[1:2])

   Duration          Date  Pulse  Maxpulse  Calories
1        60  '2020/12/02'    117       145     479.0

In [ ]:
display(df[df['Duration'] > 50].iloc[0:2, 0:3])

   Duration          Date  Pulse
0        60  '2020/12/01'    110
1        60  '2020/12/02'    117