<a href="https://colab.research.google.com/github/Shubham-Jana-Dev/Data-Science/blob/main/Pandas/04_Pandas_Rename_column.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    "Fruits":["Apple","Banana","Orange","Grapes","Papaya"],
    "Cost":[200,300,240,100,80]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
display(df)

   Fruits  Cost
0   Apple   200
1  Banana   300
2  Orange   240
3  Grapes   100
4  Papaya    80

In [6]:
df.rename(columns={"Cost":"Price"},inplace=True)

In [8]:
display(df)

   Fruits  Price
0   Apple    200
1  Banana    300
2  Orange    240
3  Grapes    100
4  Papaya     80