<a href="https://colab.research.google.com/github/Shubham-Jana-Dev/Data-Science/blob/main/Pandas/05_Pandas_Pivot_and_Pivot_Table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Pivot table allows us to reshap and transform data :)

In [10]:
import pandas as pd

In [11]:
weather_data = {
    'date': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'city': ['new york','chicago','new york','new Delhi','new york','chicago'],
    'temperature': [65,66,75,72,71,75],
    'humidity': [21,22,35,24,32,30]
}

In [12]:
df = pd.DataFrame(weather_data)

In [13]:
display(df)

       date       city  temperature  humidity
0  1/1/2017   new york           65        21
1  1/2/2017    chicago           66        22
2  1/3/2017   new york           75        35
3  1/4/2017  new Delhi           72        24
4  1/5/2017   new york           71        32
5  1/6/2017    chicago           75        30

In [14]:
df.pivot(index='date',columns='city')

         temperature                    humidity
city         chicago new Delhi new york  chicago new Delhi new york
date
1/1/2017         NaN       NaN     65.0      NaN       NaN     21.0
1/2/2017        66.0       NaN      NaN     22.0       NaN      NaN
1/3/2017         NaN       NaN     75.0      NaN       NaN     35.0
1/4/2017         NaN      72.0      NaN      NaN      24.0      NaN
1/5/2017         NaN       NaN     71.0      NaN       NaN     32.0
1/6/2017        75.0       NaN      NaN     30.0       NaN      NaN

In [15]:
df.pivot(index='date',columns='city',values='temperature')

city      chicago  new Delhi  new york
date
1/1/2017      NaN        NaN      65.0
1/2/2017     66.0        NaN       NaN
1/3/2017      NaN        NaN      75.0
1/4/2017      NaN       72.0       NaN
1/5/2017      NaN        NaN      71.0
1/6/2017     75.0        NaN       NaN

In [16]:
df.pivot(index='humidity',columns='city')

              date                     temperature
city       chicago new Delhi  new york     chicago new Delhi new york
humidity
21             NaN       NaN  1/1/2017         NaN       NaN     65.0
22        1/2/2017       NaN       NaN        66.0       NaN      NaN
24             NaN  1/4/2017       NaN         NaN      72.0      NaN
30        1/6/2017       NaN       NaN        75.0       NaN      NaN
32             NaN       NaN  1/5/2017         NaN       NaN     71.0
35             NaN       NaN  1/3/2017         NaN       NaN     75.0

In [17]:
df.pivot(index='humidity',columns='city',values='temperature')

city      chicago  new Delhi  new york
humidity
21            NaN        NaN      65.0
22           66.0        NaN       NaN
24            NaN       72.0       NaN
30           75.0        NaN       NaN
32            NaN        NaN      71.0
35            NaN        NaN      75.0

Pivot table is used to summarize of aggregate pivot data inside data frame

In [19]:
weather2_data = {
    'date': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'city': ['new york','chicago','new york','chicago','new york','chicago'],
    'temperature': [65,66,75,72,71,75],
    'humidity': [21,22,35,24,32,30]
}

In [20]:
df = pd.DataFrame(weather2_data)

In [21]:
df.pivot_table(index='city',columns='date')

         humidity                                              temperature  \
date     1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017    1/1/2017
city
chicago       NaN     22.0      NaN     24.0      NaN     30.0         NaN
new york     21.0      NaN     35.0      NaN     32.0      NaN        65.0


date     1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017
city
chicago      66.0      NaN     72.0      NaN     75.0
new york      NaN     75.0      NaN     71.0      NaN

In [22]:
df.pivot_table(index='city',columns='date',aggfunc='sum')

         humidity                                              temperature  \
date     1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017    1/1/2017
city
chicago       NaN     22.0      NaN     24.0      NaN     30.0         NaN
new york     21.0      NaN     35.0      NaN     32.0      NaN        65.0


date     1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017
city
chicago      66.0      NaN     72.0      NaN     75.0
new york      NaN     75.0      NaN     71.0      NaN

In [26]:
df.pivot_table(index='city',columns='date',aggfunc='prod')

         humidity                                              temperature  \
date     1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017    1/1/2017
city
chicago       NaN     22.0      NaN     24.0      NaN     30.0         NaN
new york     21.0      NaN     35.0      NaN     32.0      NaN        65.0


date     1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017
city
chicago      66.0      NaN     72.0      NaN     75.0
new york      NaN     75.0      NaN     71.0      NaN

In [27]:
df.pivot_table(index='city',columns='date',aggfunc='count')

         humidity                                              temperature  \
date     1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017    1/1/2017
city
chicago       NaN      1.0      NaN      1.0      NaN      1.0         NaN
new york      1.0      NaN      1.0      NaN      1.0      NaN         1.0


date     1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017
city
chicago       1.0      NaN      1.0      NaN      1.0
new york      NaN      1.0      NaN      1.0      NaN

The default aggregate function is mean :)

In [29]:
df.pivot_table(index='city',columns='date',aggfunc='mean')

         humidity                                              temperature  \
date     1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017    1/1/2017
city
chicago       NaN     22.0      NaN     24.0      NaN     30.0         NaN
new york     21.0      NaN     35.0      NaN     32.0      NaN        65.0


date     1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017
city
chicago      66.0      NaN     72.0      NaN     75.0
new york      NaN     75.0      NaN     71.0      NaN

In [30]:
df.pivot_table(index='city',columns='date',margins=False)

         humidity                                              temperature  \
date     1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017    1/1/2017
city
chicago       NaN     22.0      NaN     24.0      NaN     30.0         NaN
new york     21.0      NaN     35.0      NaN     32.0      NaN        65.0


date     1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017
city
chicago      66.0      NaN     72.0      NaN     75.0
new york      NaN     75.0      NaN     71.0      NaN

In [31]:
df.pivot_table(index="city",columns="date",margins=True)

         humidity                                                          \
date     1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017        All
city
chicago       NaN     22.0      NaN     24.0      NaN     30.0  25.333333
new york     21.0      NaN     35.0      NaN     32.0      NaN  29.333333
All          21.0     22.0     35.0     24.0     32.0     30.0  27.333333

         temperature
date        1/1/2017 1/2/2017 1/3/2017 1/4/2017 1/5/2017 1/6/2017        All
city
chicago          NaN     66.0      NaN     72.0      NaN     75.0  71.000000
new york        65.0      NaN     75.0      NaN     71.0      NaN  70.333333
All             65.0     66.0     75.0     72.0     71.0     75.0  70.666667

In [35]:
weather3_data = {
    'date':['5/1/2017','5/2/2017','5/3/2017','12/4/2017','12/5/2017','12/6/2017'],
    'city':['new york','new york','new york','new york','new york','new york'],
    'temperature':[65,66,75,72,71,75],
    'humidity':[21,22,35,24,32,30]
}

In [36]:
df = pd.DataFrame(weather3_data)

In [37]:
display(df)

        date      city  temperature  humidity
0   5/1/2017  new york           65        21
1   5/2/2017  new york           66        22
2   5/3/2017  new york           75        35
3  12/4/2017  new york           72        24
4  12/5/2017  new york           71        32
5  12/6/2017  new york           75        30

In [38]:
df['date'] = pd.to_datetime(df['date'])

In [39]:
display(df)

        date      city  temperature  humidity
0 2017-05-01  new york           65        21
1 2017-05-02  new york           66        22
2 2017-05-03  new york           75        35
3 2017-12-04  new york           72        24
4 2017-12-05  new york           71        32
5 2017-12-06  new york           75        30

In [41]:
df.pivot_table(index=pd.Grouper(freq='ME',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  26.000000   68.666667
2017-12-31  28.666667   72.666667

In [42]:
display(type(df['date'][0]))

pandas._libs.tslibs.timestamps.Timestamp