<a href="https://colab.research.google.com/github/Shubham-Jana-Dev/Data-Science/blob/main/Pandas/Pandas_03_column_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
my_data = {
    "Name":["Shubham","Deepak","Sujoy","Sujoy","Danosh","Pradip","Raj",None],
    "Salary":[34000,45000,25000,25000,20000,55000,None,90454]
}

In [ ]:
df = pd.DataFrame(my_data)

In [ ]:
display(df)

      Name   Salary
0  Shubham  34000.0
1   Deepak  45000.0
2    Sujoy  25000.0
3    Sujoy  25000.0
4   Danosh  20000.0
5   Pradip  55000.0
6      Raj      NaN
7     None  90454.0

In [ ]:
df["Bonus"] = df["Salary"]*2

In [ ]:
display(df)

      Name   Salary     Bonus
0  Shubham  34000.0   68000.0
1   Deepak  45000.0   90000.0
2    Sujoy  25000.0   50000.0
3    Sujoy  25000.0   50000.0
4   Danosh  20000.0   40000.0
5   Pradip  55000.0  110000.0
6      Raj      NaN       NaN
7     None  90454.0  180908.0

In [ ]:
df["Emplyee Id"] = pd.Series([34,67,23,23,66,12])

In [ ]:
display(df)

      Name   Salary     Bonus  Emplyee Id
0  Shubham  34000.0   68000.0        34.0
1   Deepak  45000.0   90000.0        67.0
2    Sujoy  25000.0   50000.0        23.0
3    Sujoy  25000.0   50000.0        23.0
4   Danosh  20000.0   40000.0        66.0
5   Pradip  55000.0  110000.0        12.0
6      Raj      NaN       NaN         NaN
7     None  90454.0  180908.0         NaN

In [ ]:
df = df.sort_values(by='Emplyee Id',ascending=True)

In [ ]:
display(df)

      Name   Salary     Bonus  Emplyee Id
5   Pradip  55000.0  110000.0        12.0
3    Sujoy  25000.0   50000.0        23.0
2    Sujoy  25000.0   50000.0        23.0
0  Shubham  34000.0   68000.0        34.0
4   Danosh  20000.0   40000.0        66.0
1   Deepak  45000.0   90000.0        67.0
6      Raj      NaN       NaN         NaN
7     None  90454.0  180908.0         NaN

In [ ]:
df = df.drop_duplicates(subset="Name",keep='first')

In [ ]:
display(df)

      Name   Salary     Bonus  Emplyee Id
5   Pradip  55000.0  110000.0        12.0
3    Sujoy  25000.0   50000.0        23.0
0  Shubham  34000.0   68000.0        34.0
4   Danosh  20000.0   40000.0        66.0
1   Deepak  45000.0   90000.0        67.0
6      Raj      NaN       NaN         NaN
7     None  90454.0  180908.0         NaN

In [ ]:
df = df.dropna(subset="Name")

In [ ]:
display(df)

      Name   Salary     Bonus  Emplyee Id
5   Pradip  55000.0  110000.0        12.0
3    Sujoy  25000.0   50000.0        23.0
0  Shubham  34000.0   68000.0        34.0
4   Danosh  20000.0   40000.0        66.0
1   Deepak  45000.0   90000.0        67.0
6      Raj      NaN       NaN         NaN